-- MySQL Script generated by MySQL Workbench
-- Sat May 25 12:14:17 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sam
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sam
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sam` DEFAULT CHARACTER SET utf8mb4 ;
USE `sam` ;

-- -----------------------------------------------------
-- Table `sam`.`animal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sam`.`animal` ;

CREATE TABLE IF NOT EXISTS `sam`.`animal` (
  `ID_animal` INT(11) NOT NULL AUTO_INCREMENT,
  `especie` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID_animal`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sam`.`calificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sam`.`calificacion` ;

CREATE TABLE IF NOT EXISTS `sam`.`calificacion` (
  `ID_calificacion` INT(11) NOT NULL AUTO_INCREMENT,
  `puntuacion` INT(11) NOT NULL,
  `comentario` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_calificacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sam`.`tipo_documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sam`.`tipo_documento` ;

CREATE TABLE IF NOT EXISTS `sam`.`tipo_documento` (
  `ID_documento` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID_documento`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sam`.`historial_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sam`.`historial_usuario` ;

CREATE TABLE IF NOT EXISTS `sam`.`historial_usuario` (
  `ID_historial` INT(11) NOT NULL AUTO_INCREMENT,
  `accion` VARCHAR(250) NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`ID_historial`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sam`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sam`.`usuario` ;

CREATE TABLE IF NOT EXISTS `sam`.`usuario` (
  `ID_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `documento` INT(11) NOT NULL,
  `nombre_completo` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `contraseña` VARCHAR(50) NULL DEFAULT NULL,
  `ID_documento` INT(11) NULL DEFAULT NULL,
  `ID_calificacion` INT(11) NOT NULL,
  `ID_historial` INT(11) NOT NULL,
  PRIMARY KEY (`ID_usuario`),
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`ID_documento`)
    REFERENCES `sam`.`tipo_documento` (`ID_documento`),
  CONSTRAINT `fk_usuario_calificacion1`
    FOREIGN KEY (`ID_calificacion`)
    REFERENCES `sam`.`calificacion` (`ID_calificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_historial_usuario1`
    FOREIGN KEY (`ID_historial`)
    REFERENCES `sam`.`historial_usuario` (`ID_historial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE UNIQUE INDEX `correo` ON `sam`.`usuario` (`correo` ASC) VISIBLE;

CREATE INDEX `ID_documento` ON `sam`.`usuario` (`ID_documento` ASC) VISIBLE;

CREATE INDEX `fk_usuario_calificacion1_idx` ON `sam`.`usuario` (`ID_calificacion` ASC) VISIBLE;

CREATE INDEX `fk_usuario_historial_usuario1_idx` ON `sam`.`usuario` (`ID_historial` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sam`.`raza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sam`.`raza` ;

CREATE TABLE IF NOT EXISTS `sam`.`raza` (
  `ID_raza` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `ID_animal` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_raza`),
  CONSTRAINT `raza_ibfk_1`
    FOREIGN KEY (`ID_animal`)
    REFERENCES `sam`.`animal` (`ID_animal`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `ID_animal` ON `sam`.`raza` (`ID_animal` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sam`.`imagen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sam`.`imagen` ;

CREATE TABLE IF NOT EXISTS `sam`.`imagen` (
  `ID_imagen` INT(11) NOT NULL AUTO_INCREMENT,
  `foto` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_imagen`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sam`.`vacunas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sam`.`vacunas` ;

CREATE TABLE IF NOT EXISTS `sam`.`vacunas` (
  `ID_vacuna` INT(11) NOT NULL AUTO_INCREMENT,
  `imagen_vacuna` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`ID_vacuna`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sam`.`mascota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sam`.`mascota` ;

CREATE TABLE IF NOT EXISTS `sam`.`mascota` (
  `ID_mascota` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `edad` INT(11) NULL DEFAULT NULL,
  `estado` VARCHAR(100) NULL DEFAULT NULL,
  `descripcion` VARCHAR(200) NULL DEFAULT NULL,
  `ID_animal` INT(11) NULL DEFAULT NULL,
  `ID_raza` INT(11) NULL DEFAULT NULL,
  `ID_usuario` INT(11) NULL DEFAULT NULL,
  `ID_imagen` INT(11) NOT NULL,
  `ID_vacuna` INT(11) NOT NULL,
  `ID_calificacion` INT(11) NOT NULL,
  PRIMARY KEY (`ID_mascota`),
  CONSTRAINT `mascota_ibfk_1`
    FOREIGN KEY (`ID_animal`)
    REFERENCES `sam`.`animal` (`ID_animal`),
  CONSTRAINT `mascota_ibfk_2`
    FOREIGN KEY (`ID_raza`)
    REFERENCES `sam`.`raza` (`ID_raza`),
  CONSTRAINT `mascota_ibfk_3`
    FOREIGN KEY (`ID_usuario`)
    REFERENCES `sam`.`usuario` (`ID_usuario`),
  CONSTRAINT `fk_mascota_imagen1`
    FOREIGN KEY (`ID_imagen`)
    REFERENCES `sam`.`imagen` (`ID_imagen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mascota_vacunas1`
    FOREIGN KEY (`ID_vacuna`)
    REFERENCES `sam`.`vacunas` (`ID_vacuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mascota_calificacion1`
    FOREIGN KEY (`ID_calificacion`)
    REFERENCES `sam`.`calificacion` (`ID_calificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `ID_animal` ON `sam`.`mascota` (`ID_animal` ASC) VISIBLE;

CREATE INDEX `ID_raza` ON `sam`.`mascota` (`ID_raza` ASC) VISIBLE;

CREATE INDEX `ID_usuario` ON `sam`.`mascota` (`ID_usuario` ASC) VISIBLE;

CREATE INDEX `fk_mascota_imagen1_idx` ON `sam`.`mascota` (`ID_imagen` ASC) VISIBLE;

CREATE INDEX `fk_mascota_vacunas1_idx` ON `sam`.`mascota` (`ID_vacuna` ASC) VISIBLE;

CREATE INDEX `fk_mascota_calificacion1_idx` ON `sam`.`mascota` (`ID_calificacion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sam`.`comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sam`.`comentarios` ;

CREATE TABLE IF NOT EXISTS `sam`.`comentarios` (
  `ID_comentario` INT(11) NOT NULL AUTO_INCREMENT,
  `comentario` TEXT NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `ID_usuario` INT(11) NULL DEFAULT NULL,
  `ID_mascota` INT(11) NOT NULL,
  PRIMARY KEY (`ID_comentario`),
  CONSTRAINT `comentarios_ibfk_1`
    FOREIGN KEY (`ID_usuario`)
    REFERENCES `sam`.`usuario` (`ID_usuario`),
  CONSTRAINT `fk_comentarios_mascota1`
    FOREIGN KEY (`ID_mascota`)
    REFERENCES `sam`.`mascota` (`ID_mascota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `ID_usuario` ON `sam`.`comentarios` (`ID_usuario` ASC) VISIBLE;

CREATE INDEX `fk_comentarios_mascota1_idx` ON `sam`.`comentarios` (`ID_mascota` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sam`.`notificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sam`.`notificacion` ;

CREATE TABLE IF NOT EXISTS `sam`.`notificacion` (
  `ID_notificacion` INT(11) NOT NULL AUTO_INCREMENT,
  `mensaje` TEXT NOT NULL,
  `fecha_notificacion` DATE NOT NULL,
  `leida` TINYINT(1) NULL DEFAULT 0,
  `ID_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`ID_notificacion`),
  CONSTRAINT `fk_notificacion_usuario1`
    FOREIGN KEY (`ID_usuario`)
    REFERENCES `sam`.`usuario` (`ID_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `fk_notificacion_usuario1_idx` ON `sam`.`notificacion` (`ID_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sam`.`pqrs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sam`.`pqrs` ;

CREATE TABLE IF NOT EXISTS `sam`.`pqrs` (
  `ID_pqrs` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(50) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `fecha_pqrs` DATE NOT NULL,
  `ID_usuario` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_pqrs`),
  CONSTRAINT `pqrs_ibfk_1`
    FOREIGN KEY (`ID_usuario`)
    REFERENCES `sam`.`usuario` (`ID_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE UNIQUE INDEX `correo` ON `sam`.`pqrs` (`correo` ASC) VISIBLE;

CREATE INDEX `ID_usuario` ON `sam`.`pqrs` (`ID_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sam`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sam`.`rol` ;

CREATE TABLE IF NOT EXISTS `sam`.`rol` (
  `ID_rol` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ID_rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sam`.`usuario_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sam`.`usuario_rol` ;

CREATE TABLE IF NOT EXISTS `sam`.`usuario_rol` (
  `ID_rol` INT(11) NOT NULL,
  `ID_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`ID_usuario`, `ID_rol`),
  CONSTRAINT `usuario_rol_ibfk_1`
    FOREIGN KEY (`ID_usuario`)
    REFERENCES `sam`.`usuario` (`ID_usuario`),
  CONSTRAINT `usuario_rol_ibfk_2`
    FOREIGN KEY (`ID_rol`)
    REFERENCES `sam`.`rol` (`ID_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `ID_rol` ON `sam`.`usuario_rol` (`ID_rol` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
